import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { canonicalOwnerEmail, ownerInviteMatches } from "../lib/owner-invite.mjs";
import { parseCsv } from "../lib/csv.mjs";

const root=new URL("../",import.meta.url);const read=(path)=>readFileSync(new URL(path,root),"utf8");

test("PostgreSQL migration contains normalized persistent records and safe seeds",()=>{const sql=read("supabase/migrations/0001_yone_international.sql");for(const table of ["admin_users","categories","products","product_specifications","media_assets","pending_media_uploads","blog_posts","gallery_albums","jobs","job_applications","rfqs","rfq_items","contact_inquiries","verified_testimonials","certifications","analytics_events","audit_logs","notification_outbox","push_subscriptions"])assert.match(sql,new RegExp(`create table if not exists ${table}`));assert.match(sql,/on conflict\(id\) do nothing/i);assert.match(sql,/cert_iso13485_draft[\s\S]*'draft'/);assert.doesNotMatch(sql,/insert into products|insert into jobs|insert into verified_testimonials/i);});

test("Supabase auth, authorization and storage are server-side",()=>{const auth=read("app/api/auth/login/route.ts");const admin=read("lib/admin.ts");const storage=read("lib/storage.ts");assert.match(auth,/signInWithOtp/);assert.match(auth,/lookupAdmin/);assert.match(admin,/requireAdminApi/);assert.match(admin,/role!=="owner"/);assert.match(storage,/SUPABASE_SERVICE_ROLE_KEY/);assert.match(storage,/\.storage\.from/);assert.doesNotMatch([auth,admin,storage].join("\n"),/localStorage|hardcoded.password/i);});

test("forms persist, validate origin, rate-limit and retain full RFQ details",()=>{const rfq=read("app/api/rfq/route.ts");const contact=read("app/api/contact/route.ts");const detail=read("app/admin/rfqs/[id]/page.tsx");for(const source of [rfq,contact]){assert.match(source,/assertSameOrigin/);assert.match(source,/enforceRateLimit/);assert.match(source,/consent/);}assert.match(rfq,/INSERT INTO rfqs/);assert.match(contact,/INSERT INTO contact_inquiries/);for(const field of ["target_market","required_standard","private_label","packaging","desired_date","products_text","attachment_media_id"])assert.match(detail,new RegExp(field));assert.match(detail,/FROM inquiry_notes/);});

test("PWA and push notification contracts exist",()=>{const manifest=read("public/manifest.webmanifest");const sw=read("public/sw.js");const subscribe=read("app/api/admin/push/subscribe/route.ts");const push=read("lib/push.ts");assert.match(manifest,/"display": "standalone"/);assert.match(sw,/showNotification/);assert.match(subscribe,/requireAdminApi/);assert.match(push,/setVapidDetails/);assert.match(push,/push_subscriptions/);});

test("security headers, SEO and multilingual routes exist",()=>{const config=read("next.config.ts");const sitemap=read("app/sitemap.ts");const robots=read("app/robots.ts");const i18n=read("lib/i18n.ts");for(const header of ["Content-Security-Policy","Strict-Transport-Security","X-Content-Type-Options"])assert.match(config,new RegExp(header));for(const source of ["blog_posts","gallery_albums","products"])assert.match(sitemap,new RegExp(source));assert.match(robots,/\/admin/);for(const locale of ['"en-US"','"ar"','"de"','"it"','"zh-CN"','"ja"','"ko"'])assert.match(i18n,new RegExp(locale.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.match(i18n,/locale === "ar" \? "rtl" : "ltr"/);});

test("Owner invitation accepts only configured identities",()=>{const allowlist="yoneinternational@gmail.com,loganmarkson418124+fyralix52@gmail.com";assert.equal(canonicalOwnerEmail("Logan.Markson418124+fyralix52@googlemail.com"),"loganmarkson418124@gmail.com");assert.equal(ownerInviteMatches(allowlist,"yoneinternational@gmail.com"),true);assert.equal(ownerInviteMatches(allowlist,"attacker@example.com"),false);assert.equal(ownerInviteMatches(undefined,"yoneinternational@gmail.com"),false);});

test("no password or privileged credential value is committed",()=>{const all=[read("package.json"),read(".env.example"),read("lib/runtime-env.ts"),read("README.md")].join("\n");assert.doesNotMatch(all,/gmail.{0,30}password|service[_-]?role.{0,10}(key|secret)\s*[:=]\s*["'][^"']+/i);assert.match(read(".env.example"),/SUPABASE_SERVICE_ROLE_KEY=\n/);});

test("CSV parser preserves quoted commas, newlines and escaped quotes",()=>{assert.deepEqual(parseCsv('title,body\n"Precision, verified","Line one\nLine ""two"""'),[["title","body"],["Precision, verified",'Line one\nLine "two"']]);});

test("bulk media upload uses signed storage tickets and server verification",()=>{const presign=read("app/api/admin/media/presign/route.ts");const finalize=read("app/api/admin/media/finalize/route.ts");const cancel=read("app/api/admin/media/cancel/route.ts");const client=read("components/admin-media-bulk-upload.tsx");for(const source of [presign,finalize,cancel]){assert.match(source,/assertSameOrigin/);assert.match(source,/requireAdminApi/);}assert.match(presign,/createSignedUpload/);assert.match(presign,/files\.length>20/);assert.match(presign,/50\*MB/);assert.match(presign,/pending_media_uploads/);assert.match(finalize,/validateFileBytes/);assert.match(finalize,/getObject/);assert.match(finalize,/await batch/);assert.match(finalize,/deleteObjects/);assert.match(client,/uploadToSignedUrl/);for(const endpoint of ["presign","finalize","cancel"])assert.match(client,new RegExp(`/api/admin/media/${endpoint}`));});

test("blog CSV importer is protected, bounded and always creates drafts",()=>{const importer=read("app/api/admin/blog/bulk/route.ts");const page=read("app/admin/[section]/page.tsx");assert.match(importer,/assertSameOrigin/);assert.match(importer,/requireAdminApi/);assert.match(importer,/dataRows\.length>100/);assert.match(importer,/await batch/);assert.match(importer,/'draft',NULL/);assert.match(page,/\/api\/admin\/blog\/bulk/);assert.match(page,/\/templates\/blog-import-template\.csv/);assert.match(read("public/templates/blog-import-template.csv"),/^title,slug,excerpt,body,sources,hero_media_id,author_id,category_id/);});
