import { all, first, safeAll, safeFirst } from "./db";

export type CategoryRow = { id:string; parentId:string|null; name:string; slug:string; description:string|null; sortOrder:number };
export type ProductRow = { id:string; categoryId:string; name:string; slug:string; sku:string|null; shortDescription:string|null; overview:string|null; features:string|null; applications:string|null; intendedUse:string|null; packaging:string|null; customization:string|null; disclaimer:string|null; categoryName:string; categorySlug:string; parentName:string|null; parentSlug:string|null; imageId:string|null; imageAlt:string|null };
const published = "status='published' AND deleted_at IS NULL AND (published_at IS NULL OR published_at<=unixepoch())";
const pub = (alias:string) => `${alias}.status='published' AND ${alias}.deleted_at IS NULL AND (${alias}.published_at IS NULL OR ${alias}.published_at<=unixepoch())`;

export async function publicSettings(){const rows=await safeAll<{key:string;value:string}>("SELECT key,value FROM site_settings WHERE is_private=0");return Object.fromEntries(rows.map((r)=>[r.key,r.value]));}
export async function topCategories(){return safeAll<CategoryRow>(`SELECT id,parent_id AS parentId,name,slug,description,sort_order AS sortOrder FROM categories WHERE parent_id IS NULL AND ${published} ORDER BY sort_order,name`);}
export async function subcategories(parentId:string){return safeAll<CategoryRow>(`SELECT id,parent_id AS parentId,name,slug,description,sort_order AS sortOrder FROM categories WHERE parent_id=? AND ${published} ORDER BY sort_order,name`,parentId);}
export async function categoryBySlug(slug:string){return safeFirst<CategoryRow>(`SELECT id,parent_id AS parentId,name,slug,description,sort_order AS sortOrder FROM categories WHERE slug=? AND ${published}`,slug);}
export async function productList(options:{categoryId?:string;search?:string;limit?:number;offset?:number;featured?:boolean}={}){const where=[pub("p"),"c.status='published'","c.deleted_at IS NULL","(c.published_at IS NULL OR c.published_at<=unixepoch())","(pc.id IS NULL OR (pc.status='published' AND pc.deleted_at IS NULL AND (pc.published_at IS NULL OR pc.published_at<=unixepoch())))"];const values:unknown[]=[];if(options.categoryId){where.push("p.category_id=?");values.push(options.categoryId);}if(options.search){where.push("(p.name LIKE ? OR p.sku LIKE ? OR p.short_description LIKE ?)");const q=`%${options.search.slice(0,100)}%`;values.push(q,q,q);}if(options.featured)where.push("p.featured=1");values.push(options.limit||60,options.offset||0);return safeAll<ProductRow>(`SELECT p.id,p.category_id AS categoryId,p.name,p.slug,p.sku,p.short_description AS shortDescription,p.overview,p.features,p.applications,p.intended_use AS intendedUse,p.packaging,p.customization,p.disclaimer,c.name AS categoryName,c.slug AS categorySlug,pc.name AS parentName,pc.slug AS parentSlug,pm.media_id AS imageId,ma.alt_text AS imageAlt FROM products p JOIN categories c ON c.id=p.category_id LEFT JOIN categories pc ON pc.id=c.parent_id LEFT JOIN product_media pm ON pm.product_id=p.id AND pm.is_primary=1 LEFT JOIN media_assets ma ON ma.id=pm.media_id WHERE ${where.join(" AND ")} ORDER BY p.featured DESC,p.sort_order,p.name LIMIT ? OFFSET ?`,...values);}
export async function productByPath(parentSlug:string,categorySlug:string,productSlug:string){return safeFirst<ProductRow>(`SELECT p.id,p.category_id AS categoryId,p.name,p.slug,p.sku,p.short_description AS shortDescription,p.overview,p.features,p.applications,p.intended_use AS intendedUse,p.packaging,p.customization,p.disclaimer,c.name AS categoryName,c.slug AS categorySlug,pc.name AS parentName,pc.slug AS parentSlug,pm.media_id AS imageId,ma.alt_text AS imageAlt FROM products p JOIN categories c ON c.id=p.category_id LEFT JOIN categories pc ON pc.id=c.parent_id LEFT JOIN product_media pm ON pm.product_id=p.id AND pm.is_primary=1 LEFT JOIN media_assets ma ON ma.id=pm.media_id WHERE p.slug=? AND c.slug=? AND pc.slug=? AND ${pub("p")} AND c.status='published' AND pc.status='published'`,productSlug,categorySlug,parentSlug);}
export async function productDetails(productId:string){const [specs,variants,media,related]=await Promise.all([all<{id:string;label:string;value:string}>("SELECT id,label,value FROM product_specifications WHERE product_id=? AND verified=1 ORDER BY sort_order",productId),all<{id:string;name:string;sku:string|null;details:string|null}>("SELECT id,name,sku,details FROM product_variants WHERE product_id=? ORDER BY sort_order",productId),all<{id:string;altText:string|null;caption:string|null}>("SELECT ma.id,ma.alt_text AS altText,ma.caption FROM product_media pm JOIN media_assets ma ON ma.id=pm.media_id WHERE pm.product_id=? AND ma.status='published' AND ma.visibility='public' AND ma.deleted_at IS NULL ORDER BY pm.is_primary DESC,pm.sort_order",productId),safeAll<ProductRow>(`SELECT p.id,p.category_id AS categoryId,p.name,p.slug,p.sku,p.short_description AS shortDescription,p.overview,p.features,p.applications,p.intended_use AS intendedUse,p.packaging,p.customization,p.disclaimer,c.name AS categoryName,c.slug AS categorySlug,pc.name AS parentName,pc.slug AS parentSlug,pm.media_id AS imageId,ma.alt_text AS imageAlt FROM related_products rp JOIN products p ON p.id=rp.related_product_id JOIN categories c ON c.id=p.category_id LEFT JOIN categories pc ON pc.id=c.parent_id LEFT JOIN product_media pm ON pm.product_id=p.id AND pm.is_primary=1 LEFT JOIN media_assets ma ON ma.id=pm.media_id WHERE rp.product_id=? AND ${pub("p")} ORDER BY rp.sort_order`,productId)]);return{specs,variants,media,related};}
export async function posts(){return safeAll<{id:string;title:string;slug:string;excerpt:string|null;body:string|null;sources:string|null;publishedAt:number|null;updatedDate:number|null;authorName:string|null;categoryName:string|null;heroMediaId:string|null}>(`SELECT bp.id,bp.title,bp.slug,bp.excerpt,bp.body,bp.sources,bp.published_at AS publishedAt,bp.updated_date AS updatedDate,a.name AS authorName,bc.name AS categoryName,bp.hero_media_id AS heroMediaId FROM blog_posts bp LEFT JOIN authors a ON a.id=bp.author_id LEFT JOIN blog_categories bc ON bc.id=bp.category_id WHERE ${pub("bp")} ORDER BY bp.published_at DESC`);}
export async function postBySlug(slug:string){return first<Awaited<ReturnType<typeof posts>>[number]>(`SELECT bp.id,bp.title,bp.slug,bp.excerpt,bp.body,bp.sources,bp.published_at AS publishedAt,bp.updated_date AS updatedDate,a.name AS authorName,bc.name AS categoryName,bp.hero_media_id AS heroMediaId FROM blog_posts bp LEFT JOIN authors a ON a.id=bp.author_id LEFT JOIN blog_categories bc ON bc.id=bp.category_id WHERE bp.slug=? AND ${pub("bp")}`,slug);}
export async function albums(){return safeAll<{id:string;name:string;slug:string;description:string|null;eventDate:number|null;imageId:string|null}>(`SELECT ga.id,ga.name,ga.slug,ga.description,ga.event_date AS eventDate,(SELECT gi.media_id FROM gallery_images gi WHERE gi.album_id=ga.id ORDER BY gi.sort_order LIMIT 1) AS imageId FROM gallery_albums ga WHERE ${pub("ga")} ORDER BY ga.event_date DESC,ga.name`);}
export async function albumBySlug(slug:string){return safeFirst<{id:string;name:string;slug:string;description:string|null;eventDate:number|null}>(`SELECT ga.id,ga.name,ga.slug,ga.description,ga.event_date AS eventDate FROM gallery_albums ga WHERE ga.slug=? AND ${pub("ga")}`,slug);}
export async function albumImages(albumId:string){return safeAll<{id:string;mediaId:string;caption:string|null;altText:string|null;imageDate:number|null}>(`SELECT gi.id,gi.media_id AS mediaId,gi.caption,coalesce(gi.alt_text,ma.alt_text) AS altText,gi.image_date AS imageDate FROM gallery_images gi JOIN media_assets ma ON ma.id=gi.media_id WHERE gi.album_id=? AND ma.visibility='public' AND ma.status='published' AND ma.deleted_at IS NULL ORDER BY gi.sort_order,gi.created_at`,albumId);}
export async function jobsList(){return safeAll<{id:string;title:string;slug:string;department:string|null;location:string|null;employmentType:string|null;description:string|null;requirements:string|null;applicationInstructions:string|null;publishedAt:number|null;closingDate:number|null}>(`SELECT id,title,slug,department,location,employment_type AS employmentType,description,requirements,application_instructions AS applicationInstructions,published_at AS publishedAt,closing_date AS closingDate FROM jobs WHERE ${published} AND (closing_date IS NULL OR closing_date>=unixepoch()) ORDER BY published_at DESC`);}
export async function jobBySlug(slug:string){return safeFirst<Awaited<ReturnType<typeof jobsList>>[number]>(`SELECT id,title,slug,department,location,employment_type AS employmentType,description,requirements,application_instructions AS applicationInstructions,published_at AS publishedAt,closing_date AS closingDate FROM jobs WHERE slug=? AND ${published} AND (closing_date IS NULL OR closing_date>=unixepoch())`,slug);}
export async function latestCatalog(){return safeFirst<{id:string;originalName:string}>("SELECT id,original_name AS originalName FROM media_assets WHERE kind='catalog' AND visibility='public' AND status='published' AND deleted_at IS NULL ORDER BY created_at DESC LIMIT 1");}
