import { first, id, unix } from "./db";
import { runtimeEnv } from "./runtime-env";

const EMAIL = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
export class ValidationError extends Error { status = 400; }
export function clean(value: FormDataEntryValue | null, max = 5000) { return typeof value === "string" ? value.trim().slice(0, max) : ""; }
export function required(value: FormDataEntryValue | null, label: string, max = 5000) { const v = clean(value, max); if (!v) throw new ValidationError(`${label} is required.`); return v; }
export function email(value: FormDataEntryValue | null) { const v = required(value, "Business email", 254).toLowerCase(); if (!EMAIL.test(v)) throw new ValidationError("Enter a valid business email."); return v; }
export function slug(value: FormDataEntryValue | null, fallback = "") { const v = (clean(value, 120) || fallback).toLowerCase().normalize("NFKD").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""); if (!v) throw new ValidationError("A valid slug is required."); return v; }
export function safeReturnTo(value: FormDataEntryValue | null, fallback: string) { const v = clean(value, 400); return v.startsWith("/") && !v.startsWith("//") && !v.includes("\\") && !v.includes("://") ? v : fallback; }
export async function assertSameOrigin(request: Request) { const origin = request.headers.get("origin"); const site = request.headers.get("sec-fetch-site"); if (!origin && !site) throw new ValidationError("Request origin could not be verified."); if (site && !["same-origin", "same-site", "none"].includes(site)) throw new ValidationError("Cross-site request rejected."); if (origin && new URL(origin).host !== new URL(request.url).host) throw new ValidationError("Request origin rejected."); }
export async function enforceRateLimit(request: Request, scope: string, limit: number, seconds: number) { const env=runtimeEnv();if (!env.RATE_LIMIT_SALT) throw new Error("Rate-limit protection is not configured."); const ip = request.headers.get("x-nf-client-connection-ip") || request.headers.get("x-forwarded-for")?.split(",")[0] || request.headers.get("cf-connecting-ip") || "unknown"; const input = `${scope}|${new Date().toISOString().slice(0,10)}|${ip}|${request.headers.get("user-agent") || ""}|${env.RATE_LIMIT_SALT}`; const hash = [...new Uint8Array(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(input)))].map((b) => b.toString(16).padStart(2, "0")).join(""); const key = `${scope}:${hash}`; const now = unix(); const reset = now + seconds; const row = await first<{count:number}>("INSERT INTO rate_limits(bucket,count,reset_at,updated_at) VALUES(?,1,?,?) ON CONFLICT(bucket) DO UPDATE SET count=CASE WHEN rate_limits.reset_at<=? THEN 1 ELSE rate_limits.count+1 END,reset_at=CASE WHEN rate_limits.reset_at<=? THEN ? ELSE rate_limits.reset_at END,updated_at=? RETURNING count",key,reset,now,now,now,reset,now); if (!row || Number(row.count) > limit) throw new ValidationError("Too many requests. Please try again later."); }
export function reference(prefix: string) { return `${prefix}-${new Date().toISOString().slice(0,10).replaceAll("-","")}-${id("").slice(-8).toUpperCase()}`; }
export function validateFileBytes(bytesBuffer:ArrayBuffer,fileName:string,maxBytes:number,pdfOnly=false){if(!bytesBuffer.byteLength||bytesBuffer.byteLength>maxBytes)throw new ValidationError(`File must be smaller than ${Math.round(maxBytes/1024/1024)} MB.`);const bytes=new Uint8Array(bytesBuffer.slice(0,16));const pdf=new TextDecoder().decode(bytes.slice(0,5))==="%PDF-";const jpeg=bytes[0]===0xff&&bytes[1]===0xd8&&bytes[2]===0xff;const png=bytes[0]===0x89&&bytes[1]===0x50&&bytes[2]===0x4e&&bytes[3]===0x47;const webp=new TextDecoder().decode(bytes.slice(0,4))==="RIFF"&&new TextDecoder().decode(bytes.slice(8,12))==="WEBP";if(pdfOnly?!pdf:!(pdf||jpeg||png||webp))throw new ValidationError("File type or signature is not allowed.");const allowed=pdf?["pdf"]:jpeg?["jpg","jpeg"]:png?["png"]:["webp"];const extension=fileName.split(".").pop()?.toLowerCase()||"";if(!allowed.includes(extension))throw new ValidationError("File extension does not match its content.");return{extension,mime:pdf?"application/pdf":jpeg?"image/jpeg":png?"image/png":"image/webp"};}
export async function validateUpload(file:File,maxBytes:number,pdfOnly=false){const bytes=await file.arrayBuffer();return{bytes,...validateFileBytes(bytes,file.name,maxBytes,pdfOnly)};}
