import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminShell } from "../../../components/admin-shell";
import { requireAdmin } from "../../../lib/admin";
import { adminResources } from "../../../lib/admin-resources";
import { all, first } from "../../../lib/db";

type Row={id:string;name:string;slug:string;status:string;detail:string|null;updatedAt:number};
type Query={edit?:string;ok?:string;error?:string};

const special:Record<string,{label:string;sql:string;columns:string[]}>={
  rfqs:{label:"RFQs",sql:"SELECT id,reference,full_name,email,company,country,status,assigned_to,created_at FROM rfqs WHERE deleted_at IS NULL ORDER BY created_at DESC LIMIT 250",columns:["reference","full_name","email","company","country","status","assigned_to","created_at"]},
  contacts:{label:"Contact enquiries",sql:"SELECT id,reference,full_name,email,company,country,status,assigned_to,created_at FROM contact_inquiries WHERE deleted_at IS NULL ORDER BY created_at DESC LIMIT 250",columns:["reference","full_name","email","company","country","status","assigned_to","created_at"]},
  applications:{label:"Career applications",sql:"SELECT ja.id,ja.reference,ja.full_name,ja.email,j.title AS job,status,assigned_to,ja.created_at FROM job_applications ja JOIN jobs j ON j.id=ja.job_id WHERE ja.deleted_at IS NULL ORDER BY ja.created_at DESC LIMIT 250",columns:["reference","full_name","email","job","status","assigned_to","created_at"]},
  media:{label:"Media library",sql:"SELECT id,original_name,kind,visibility,status,size_bytes,created_at FROM media_assets WHERE deleted_at IS NULL ORDER BY created_at DESC LIMIT 250",columns:["original_name","kind","visibility","status","size_bytes","created_at"]},
  analytics:{label:"Privacy-friendly analytics",sql:"SELECT event_name,count(*) AS total,max(occurred_at) AS last_seen FROM analytics_events WHERE is_bot=0 GROUP BY event_name ORDER BY total DESC LIMIT 100",columns:["event_name","total","last_seen"]},
  settings:{label:"Site settings",sql:"SELECT key,value,is_private,updated_at FROM site_settings ORDER BY key",columns:["key","value","is_private","updated_at"]},
  retention:{label:"Retention controls",sql:"SELECT record_type,retention_days,mode,updated_at FROM retention_policies ORDER BY record_type",columns:["record_type","retention_days","mode","updated_at"]},
  redirects:{label:"Redirects",sql:"SELECT id,source_path,destination_path,status_code,active,created_at FROM redirects ORDER BY source_path",columns:["source_path","destination_path","status_code","active","created_at"]},
  users:{label:"Admin users",sql:"SELECT id,email,display_name,role,status,last_login_at,created_at FROM admin_users ORDER BY created_at",columns:["email","display_name","role","status","last_login_at","created_at"]},
  audit:{label:"Audit log",sql:"SELECT id,actor_email,action,target_type,target_id,created_at FROM audit_logs ORDER BY created_at DESC LIMIT 300",columns:["actor_email","action","target_type","target_id","created_at"]},
};

export default async function AdminSection({params,searchParams}:{params:Promise<{section:string}>;searchParams:Promise<Query>}){
  const {section}=await params;const query=await searchParams;const admin=await requireAdmin(`/admin/${section}`);
  const resource=adminResources[section];
  if(resource){
    if(resource.ownerOnly&&admin.role!=="owner")return <AdminShell admin={admin}><div className="admin-page"><h1>Owner permission required</h1><p>This publishing area is restricted to the Owner.</p></div></AdminShell>;
    const [rows,edit]=await Promise.all([all<Row>(resource.listSql),query.edit?first<Record<string,unknown>>(`SELECT * FROM ${resource.table} WHERE id=?`,query.edit):Promise.resolve(null)]);
    return <AdminShell admin={admin}><div className="admin-page"><div className="admin-heading"><div><p className="eyebrow">Content management</p><h1>{resource.label}</h1></div></div>
      {query.ok&&<p className="form-success" role="status">{query.ok}</p>}{query.error&&<p className="form-error" role="alert">{query.error}</p>}
      {section==="blog"&&<section className="admin-panel"><h2>Bulk import blog drafts</h2><p>Upload up to 100 articles from CSV. Every imported article is saved as Draft for review before publication.</p><form className="admin-form compact" action="/api/admin/blog/bulk" method="post" encType="multipart/form-data"><label><span>CSV file</span><input required type="file" name="file" accept=".csv,text/csv"/></label><div className="button-row"><button className="button button-dark" type="submit">Import blog drafts</button><a className="button button-outline" href="/templates/blog-import-template.csv" download>Download CSV template</a></div></form></section>}
      <section className="admin-panel"><h2>{edit?"Edit record":"Add new"}</h2><form className="admin-form" action="/api/admin/content" method="post"><input type="hidden" name="resource" value={section}/>{edit&&<input type="hidden" name="item_id" value={String(edit.id)}/>}
        {resource.fields.map((field)=>{const value=edit?.[field.name];return <label key={field.name}><span>{field.label}{field.required?" *":""}</span>{field.type==="textarea"?<textarea name={field.name} required={field.required} defaultValue={value==null?"":String(value)}/>:field.type==="select"?<select name={field.name} required={field.required} defaultValue={value==null?(field.name==="status"?"draft":""):String(value)}>{field.options?.map((option)=><option value={option.value} key={option.value}>{option.label}</option>)}</select>:<input name={field.name} type={field.type||"text"} required={field.required} defaultValue={value==null?"":String(value)}/>}</label>})}
        <div className="button-row"><button className="button button-dark" type="submit">{edit?"Save changes":"Create record"}</button>{edit&&<Link className="button button-outline" href={`/admin/${section}`}>Cancel</Link>}</div>
      </form></section>
      <section className="admin-panel"><h2>Records</h2>{rows.length?<div className="admin-table-wrap"><table><thead><tr><th>Name</th><th>Slug / ID</th><th>Status</th><th>Detail</th><th>Actions</th></tr></thead><tbody>{rows.map((row)=><tr key={row.id}><td>{row.name}</td><td>{row.slug||row.id}</td><td><span className={`status-pill status-${row.status}`}>{row.status}</span></td><td>{row.detail||"—"}</td><td><div className="table-actions"><Link href={`/admin/${section}?edit=${row.id}`}>Edit</Link>{resource.lifecycle&&<form action="/api/admin/lifecycle" method="post"><input type="hidden" name="resource" value={section}/><input type="hidden" name="item_id" value={row.id}/><select name="action" aria-label={`Change ${row.name} status`} defaultValue=""><option value="" disabled>Change…</option><option value="draft">Draft</option><option value="publish">Publish</option><option value="archive">Archive</option><option value="trash">Trash</option></select><button type="submit">Apply</button></form>}</div></td></tr>)}</tbody></table></div>:<p>No records yet.</p>}</section>
    </div></AdminShell>;
  }
  const config=special[section];if(!config)notFound();
  if(["settings","retention","redirects","users","audit"].includes(section)&&admin.role!=="owner")return <AdminShell admin={admin}><div className="admin-page"><h1>Owner permission required</h1></div></AdminShell>;
  const rows=await all<Record<string,unknown>>(config.sql);
  return <AdminShell admin={admin}><div className="admin-page"><div className="admin-heading"><div><p className="eyebrow">Administration</p><h1>{config.label}</h1></div>{["rfqs","contacts","applications"].includes(section)&&<a className="button button-dark" href={`/api/admin/export/${section}`}>Export CSV</a>}</div>
    {query.ok&&<p className="form-success" role="status">{query.ok}</p>}{query.error&&<p className="form-error" role="alert">{query.error}</p>}
    {section==="media"&&<section className="admin-panel"><h2>Bulk upload media or catalogs</h2><p>Select up to 20 files in one upload (maximum 50 MB total). Each file is validated before anything is saved.</p><form className="admin-form compact" action="/api/admin/media" method="post" encType="multipart/form-data"><label><span>Files (PDF, JPEG, PNG, WebP)</span><input required multiple type="file" name="files" accept=".pdf,.jpg,.jpeg,.png,.webp"/></label><label><span>Kind</span><select name="kind"><option value="image">Images</option><option value="catalog">Downloadable catalogs</option><option value="datasheet">Datasheets</option></select></label><label><span>Visibility</span><select name="visibility"><option value="private">Private draft</option><option value="public">Public</option></select></label><label><span>Shared alt-text prefix (optional)</span><input name="alt_text" placeholder="Product instruments"/></label><button className="button button-dark" type="submit">Upload selected files</button></form></section>}
    {section==="users"&&<section className="admin-panel"><h2>Invite administrator</h2><form className="admin-form compact" action="/api/admin/users" method="post"><label><span>Email</span><input name="email" type="email" required/></label><label><span>Display name</span><input name="display_name"/></label><label><span>Role</span><select name="role"><option value="editor">Editor</option><option value="owner">Owner</option></select></label><button className="button button-dark">Add approved user</button></form></section>}
    {section==="settings"&&<section className="admin-panel"><h2>Update setting</h2><form className="admin-form compact" action="/api/admin/settings" method="post"><label><span>Setting key</span><input name="key" required/></label><label><span>Value</span><input name="value" required/></label><label><span>Private</span><select name="is_private"><option value="0">Public</option><option value="1">Private</option></select></label><button className="button button-dark">Save setting</button></form></section>}
    {section==="retention"&&<section className="admin-panel"><h2>Update retention policy</h2><form className="admin-form compact" action="/api/admin/retention" method="post"><label><span>Record type</span><select name="record_type"><option value="rfqs">RFQs</option><option value="contact_inquiries">Contact enquiries</option><option value="job_applications">Job applications</option><option value="analytics_events">Analytics</option></select></label><label><span>Retention days</span><input name="retention_days" type="number" min="1" max="3650" required/></label><label><span>Mode</span><select name="mode"><option value="disabled">Disabled</option><option value="delete">Delete after period</option></select></label><button className="button button-dark">Save policy</button></form></section>}
    {section==="redirects"&&<section className="admin-panel"><h2>Add redirect</h2><form className="admin-form compact" action="/api/admin/redirects" method="post"><label><span>Source path</span><input name="source_path" placeholder="/old-page" required/></label><label><span>Destination path</span><input name="destination_path" placeholder="/new-page" required/></label><label><span>Status</span><select name="status_code"><option value="301">301 permanent</option><option value="302">302 temporary</option></select></label><button className="button button-dark">Save redirect</button></form></section>}
    <section className="admin-panel"><div className="admin-table-wrap"><table><thead><tr>{config.columns.map((c)=><th key={c}>{c.replaceAll("_"," ")}</th>)}{["rfqs","contacts","applications"].includes(section)&&<th>{section==="rfqs"?"Details & workflow":"Workflow"}</th>}</tr></thead><tbody>{rows.map((row,index)=><tr key={String(row.id||index)}>{config.columns.map((column)=><td key={column}>{column.includes("created_at")||column.includes("last_seen")||column.includes("last_login")?row[column]?new Date(Number(row[column])*1000).toLocaleString("en-GB"):"—":String(row[column]??"—")}</td>)}{["rfqs","contacts","applications"].includes(section)&&<td>{section==="rfqs"&&<Link className="admin-detail-link" href={`/admin/rfqs/${String(row.id)}`}>View full enquiry</Link>}<form className="workflow-form" action="/api/admin/inquiries" method="post"><input type="hidden" name="type" value={section}/><input type="hidden" name="id" value={String(row.id)}/><select name="status" defaultValue={String(row.status||"new")}><option value="new">New</option><option value="reviewing">Reviewing</option><option value="quoted">Quoted</option><option value="closed">Closed</option></select><input name="assigned_to" placeholder="Assign to" defaultValue={String(row.assigned_to||"")}/><input name="note" placeholder="Internal note"/><button>Save</button></form></td>}</tr>)}</tbody></table></div></section>
  </div></AdminShell>;
}
